version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    # See https://github.com/readthedocs/readthedocs.org/issues/4912
    # See https://github.com/readthedocs/readthedocs.org/issues/4912#issuecomment-1110189914
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
      - poetry export --with dev -f requirements.txt --without-hashes --output docs/requirements.txt
    post_install:
      - poetry install

python:
   install:
   - requirements: docs/requirements.txt