site_name: nprompter

theme:
  name: material
  logo: images/nprompter-dark.png

nav:
  - Home: index.md
  - Configuring Notion:
    - Create a database: configuring-notion/create-database.md
    - Create an integration: configuring-notion/create-integration.md
  - About nprompter:
    - Usage: nprompter/usage.md
    - Configuration file: nprompter/configuration-file.md
    - Multi-database support: nprompter/multi-database-support.md
    - Alternatives: nprompter/alternatives.md
    - Create a teleprompter: nprompter/create-teleprompter.md