[build]
base = "deploy_examples/netlify"
publish = "deploy_examples/netlify/.content"
command = "nprompter build c68ccc052d1b4eaaa3091e637f7011c0"

[context.production]
environment = { PYTHON_VERSION = "3.8" }
# Don't forget to add your NOTION_API_KEY to the environment using the Netlify UI
# NEVER put the value of NOTION_API_KEY in a plain text file!
